<a href="https://colab.research.google.com/github/ozgurgungoro/Yapay-Zeka-ve-Makine-Ogrenimi-Derslerim/blob/main/Numpy_derslerim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ders Kaynağı: https://www.youtube.com/watch?v=yzxSGeb1DbM&list=PL3ED48mWmYxraLfbHEn4Xjii3mBilFIka&index=1**

In [202]:
import numpy as np

In [2]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

**2-Numpy ile Nokta Dogru Düzlem ve Uzay**

In [9]:
skaler=np.array(90)
print(skaler)

90


In [10]:
vektor=np.array([1,2,3,4,5,6])
print(vektor)

[1 2 3 4 5 6]


In [11]:
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
tensor=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(tensor)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


**3-Neden Numpy?**

In [13]:
import time

In [16]:
z1=time.time()
liste=[]
for a in range(1_000_000):
  kuvvet=a**100
  liste.append(kuvvet)



z2=time.time()


print(z2-z1)

3.1495211124420166


In [17]:
z3=time.time()

liste2=np.arange(1_000_000)**100


z4=time.time()

print(z4-z3)

0.02875208854675293


# Ders 3 Index ve Slice

In [23]:
vektor=np.array([0,2,4,5,6,7,8,15])

In [24]:
vektor[3]

5

In [25]:
vektor[0]

0

In [26]:
vektor[-1]

15

In [29]:
vektor[1:3]

array([2, 4])

In [30]:
vektor[:5]

array([0, 2, 4, 5, 6])

In [31]:
vektor[2:6:2]

array([4, 6])

**Ders 5 Size,Shape,Dtype,ndim**

In [32]:
vektor=np.array([1,2,3,4,5,6])
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
print(vektor)

[1 2 3 4 5 6]


In [34]:
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
vektor.size

6

In [37]:
matris.size

9

In [38]:
vektor.shape

(6,)

In [39]:
matris.shape

(3, 3)

In [40]:
vektor.ndim

1

In [41]:
matris.ndim

2

In [42]:
vektor.dtype

dtype('int64')

In [43]:
matris.dtype

dtype('int64')

In [44]:
type(vektor)

numpy.ndarray

In [45]:
type(matris)

numpy.ndarray

**DERS6 - Numpy Veri Tipi Değiştirme**

In [50]:
sayilar=np.array([1,2,3,4,5.0,6,"Özgür"])

In [51]:
sayilar.dtype

dtype('<U32')

In [52]:
sayilar=np.array([1,2,3,4,5.0,6])

In [53]:
sayilar.dtype

dtype('float64')

In [54]:
sayilar=np.array([1,2,3,4,5])

In [55]:
sayilar.dtype

dtype('int64')

In [57]:
sayilar=sayilar.astype("int8")
sayilar.dtype

dtype('int8')

In [59]:
sayilar=np.array([1,2,3,4,5,6],dtype="int8")
sayilar.dtype

dtype('int8')

In [60]:
tarih=np.array(["2023-01-01"])
tarih.dtype

dtype('<U10')

In [62]:
tarih=tarih.astype("datetime64[ns]")
tarih.dtype

dtype('<M8[ns]')

**DERS7 Matrislerde Slice**

In [63]:
matris=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [64]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
matris[0]

array([1, 2, 3, 4])

In [66]:
matris[1]

array([5, 6, 7, 8])

In [67]:
matris[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [70]:
matris[0,:2]

array([1, 2])

In [72]:
matris[0:4,0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [75]:
matris[0:4,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [77]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [78]:
matris[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

**Ders8- Random Matris Oluşturma**

In [80]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [85]:
np.random.randint(0,5,(4,4))

array([[4, 4, 0, 0],
       [4, 2, 2, 2],
       [2, 0, 4, 0],
       [3, 1, 3, 2]])

In [87]:
np.random.randint(0,10,(4,4))/10

array([[0.1, 0.4, 0.1, 0.1],
       [0. , 0.9, 0.4, 0.6],
       [0.6, 0.1, 0.5, 0.6],
       [0.6, 0.4, 0.9, 0.6]])

**Ders9- Arange ile Vektör Oluşturma**

In [91]:
liste=[1,2,3,4,5,6]
range=(1000000)


In [92]:
milyon=np.arange(1000000)

In [93]:
milyon

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [96]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [98]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

**Ders 10 - linspace() ile Vektör Oluşturma**

In [99]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [101]:
np.arange(5,10,2)

array([5, 7, 9])

In [102]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

**Ders11 Numpy Yeniden Boyutlandırma reshape() Metodu**

In [103]:
m1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [104]:
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
m1.shape

(3, 4)

In [106]:
m1.size

12

In [107]:
m1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [108]:
m1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [111]:
m1x=m1.reshape(12)

In [112]:
m1x.shape

(12,)

In [113]:
np.random.randint(0,2,(8,6)).reshape(4,12)

array([[1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1],
       [0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]])

In [114]:
np.linspace(0,20,30).reshape(6,5)

array([[ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069],
       [ 3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655],
       [ 6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241],
       [10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828],
       [13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414],
       [17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ]])

**DERS12 copy() ve view() Metotları**

In [116]:
matris=np.random.randint(0,5,(4,4))

In [122]:
matris

array([[4, 2, 1, 0],
       [1, 0, 0, 2],
       [3, 3, 3, 1],
       [4, 0, 0, 1]])

In [123]:
matris2=matris.view()

In [124]:
matris2[0]=[9,9,9,9]

In [125]:
matris2

array([[9, 9, 9, 9],
       [1, 0, 0, 2],
       [3, 3, 3, 1],
       [4, 0, 0, 1]])

In [126]:
matris

array([[9, 9, 9, 9],
       [1, 0, 0, 2],
       [3, 3, 3, 1],
       [4, 0, 0, 1]])

In [127]:
matris3=np.random.randint(0,5,(4,4))

In [128]:
matris3

array([[4, 3, 3, 1],
       [4, 4, 1, 4],
       [3, 2, 3, 1],
       [4, 2, 1, 2]])

In [129]:
matris4=matris3.copy()

In [131]:
matris4

array([[4, 3, 3, 1],
       [4, 4, 1, 4],
       [3, 2, 3, 1],
       [4, 2, 1, 2]])

In [132]:
matris4[0]=[7,7,7,7]

In [133]:
matris4

array([[7, 7, 7, 7],
       [4, 4, 1, 4],
       [3, 2, 3, 1],
       [4, 2, 1, 2]])

In [134]:
matris3

array([[4, 3, 3, 1],
       [4, 4, 1, 4],
       [3, 2, 3, 1],
       [4, 2, 1, 2]])

**Dera13- ones() zeros() ve full() Matris Oluşturma Metotları**

In [135]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [137]:
np.zeros((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [139]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [140]:
np.full((4,4),19)

array([[19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19]])

**Ders14- Numpy eye() diag() ve identity() Metotları**

In [141]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [146]:
np.eye(5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [147]:
np.diag([1,1,1,1,1,1])

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [150]:
np.diag([1,2,3,2,1])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [151]:
r=np.random.randint(0,3,(5,5))
print(r)

[[2 2 1 1 2]
 [2 2 0 2 2]
 [0 2 0 0 0]
 [1 1 2 2 0]
 [0 2 0 2 1]]


In [152]:
np.diag(r)

array([2, 2, 0, 2, 1])

In [153]:
np.diag(np.diag(r))

array([[2, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

**DERS 15 Matrislerde Matematiksel İşlemler toplama çıkarma çarpma bölme fark**

In [155]:
m1 = np.ones((5,5))
m2 = np.full((5,5),19)

In [156]:
m1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [157]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [158]:
m1 * 4

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [159]:
m2 + 3

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [160]:
m1+m2

array([[20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.]])

In [161]:
m2-m1

array([[18., 18., 18., 18., 18.],
       [18., 18., 18., 18., 18.],
       [18., 18., 18., 18., 18.],
       [18., 18., 18., 18., 18.],
       [18., 18., 18., 18., 18.]])

In [162]:
m2/3

array([[6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333]])

In [163]:
m2//3

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [164]:
m2%3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [165]:
m3=np.full((5,6),2)

In [166]:
m3

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [167]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [168]:
m3.shape

(5, 6)

In [169]:
m2.shape

(5, 5)

In [170]:
m2+m3

ValueError: operands could not be broadcast together with shapes (5,5) (5,6) 

In [171]:
m3.reshape(30)[:25].reshape(5,5)+m2

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

In [172]:
m1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [177]:
m1[0]=m1 [0]*3

In [178]:
m1

array([[3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [179]:
m5=np.arange(5).reshape((5,1))

In [180]:
m5

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [181]:
m1*m5

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [182]:
m1/m5

<ipython-input-182-d597fd457727>:1: RuntimeWarning: divide by zero encountered in divide
  m1/m5


array([[       inf,        inf,        inf,        inf,        inf],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.25      ]])

In [183]:
m1+m5

array([[3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [184]:
m6=m1+m5

In [185]:
m6

array([[3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [186]:
m6*np.diag(m6)

array([[ 9.,  6.,  9., 12., 15.],
       [ 6.,  4.,  6.,  8., 10.],
       [ 9.,  6.,  9., 12., 15.],
       [12.,  8., 12., 16., 20.],
       [15., 10., 15., 20., 25.]])

**DERS 16 Numpy ile Mantıksal Operatörler ve Filtreleme**

In [187]:
matris=np.random.randint(0,10,(5,5))

In [188]:
matris

array([[9, 5, 4, 5, 4],
       [0, 2, 7, 4, 5],
       [0, 4, 7, 9, 3],
       [0, 8, 2, 0, 6],
       [9, 9, 8, 3, 1]])

In [189]:
matris>5

array([[ True, False, False, False, False],
       [False, False,  True, False, False],
       [False, False,  True,  True, False],
       [False,  True, False, False,  True],
       [ True,  True,  True, False, False]])

In [190]:
matris[matris>5]

array([9, 7, 7, 9, 8, 6, 9, 9, 8])

In [191]:
matris[matris<5]

array([4, 4, 0, 2, 4, 0, 4, 3, 0, 2, 0, 3, 1])

In [192]:
matris[matris==5]

array([5, 5, 5])

In [193]:
matris[matris==7].size

2

In [195]:
matris[matris!=7]

array([9, 5, 4, 5, 4, 0, 2, 4, 5, 0, 4, 9, 3, 0, 8, 2, 0, 6, 9, 9, 8, 3,
       1])

In [196]:
matris

array([[9, 5, 4, 5, 4],
       [0, 2, 7, 4, 5],
       [0, 4, 7, 9, 3],
       [0, 8, 2, 0, 6],
       [9, 9, 8, 3, 1]])

In [197]:
matris%2==0

array([[False, False,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True,  True, False, False, False],
       [ True,  True,  True,  True,  True],
       [False, False,  True, False, False]])

In [198]:
matris[matris%2==0]

array([4, 4, 0, 2, 4, 0, 4, 0, 8, 2, 0, 6, 8])

In [199]:
matris[matris%2==0]

array([4, 4, 0, 2, 4, 0, 4, 0, 8, 2, 0, 6, 8])

In [200]:
sifir=matris!=0
cift=matris%2==0

In [201]:
matris[cift & sifir]

array([4, 4, 2, 4, 4, 8, 2, 6, 8])